### ISSUE TITLE
Spaces page banner issue, bug with YUI Compressor and Calc function

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#427] opened 2016-08-04 12:17 UTC
Wagon uses yui compressor to minify css, but the compressor removes whitespaces from calc function. More info [here](https://github.com/sstephenson/ruby-yui-compressor/issues/42) and possible fix [here](https://github.com/yui/yuicompressor/issues/59). YUI compressor hasn't released a new version since 2013.

**Comment by cappadona** [comment] 2016-08-09 17:16
Unable to reproduce this locally regardless of hosting the site via Wagon or Engine. I just deployed to dev for #300 and that also resolved the behavior there.

@tap87, I'm thinking this is an isolated situation for you since I believe you're the only one who has deployed to dev in the past two weeks. I suspect it may be related to the introduction of the semantic-ui fork which resulted in duplication (#431), which I will be addressing soon.

Please let me know if you're still seeing this on your local instance, but for now I'm marking this as  `wontfix`. Thanks.

**Closed** 2016-08-09 20:11 UTC
Labels: bug, wontfix
