### ISSUE TITLE
WYSIHTML editor - tables, lists, etc.

### ISSUE THREAD

**Issue by dbranchini** [cul-it/mann-wagon#409] opened 2016-07-22 17:48 UTC
Tobi reported this so I don't have the details but didn't want to lose sight of it.  If I understood it correctly, she said she didn't have enough control to the type of tables or lists she wanted.  I'm assuming this means in styles and layout.

**Comment by cappadona** [comment] 2016-09-12 14:04
Duplicate of #79

**Closed by cappadona** 2016-09-12 14:04 UTC
Labels: wontfix
