### ISSUE TITLE
Evaluate LibCal Equipment & Spaces module as replacement for Room Bookings module

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#847] opened 2017-04-03 19:00 UTC
We suspect that Springshare is going phase out the Room Bookings module in LibCal, since their new Equipment & Spaces reservation module does pretty much the same thing (but has a read/write API!). There are instructions on how to migrate existing room data into the new module - sadly, we did not follow this and have hit a snag and accidentally pre-migrated all CUL room bookings into the Uris Library location. Whoops. We have reached out to Springshare to see if they can reset our migration so we can start over. BUT! Lesson learned: before migrating the data over, you must select the correct library location for the spaces, because you cannot change the location data after the migration has begun.

Also, it's all or nothing - you can't just go in and migrate Mann's rooms. If you start the pre-migration process, all CUL rooms get migrated. So we need to make sure all the library locations are in there before we get started with the migration.

Will update once we've heard back from Springshare.

**Comment by sew268** [comment] 2017-04-03 19:10
LibCal makes it sound easy to adjust availability but not sure how this affects the public calendar http://support.springshare.com/libcal/equipment-setup/overview

Also, each space (some spaces can be grouped like 100 & 102) that needs to be accounted for would need to be it's own location with an hours template created for that space.  To change availability, we'd need to add in hours exceptions templates.

**Comment by eeh53** [comment] 2017-04-04 15:01
Issues with LibCal Spaces & Equipment Module

- We can’t change location of our spaces without it affecting the location of ALL of the spaces. If we tie all Mann spaces to one location, they are all tied to one set of hours for Mann, and some of our spaces have different availability hours (our only option then seems to be entering each space/room group as it’s own location). Also, is there really only one set of terms & conditions for all spaces?? And we can’t customize email templates for specific rooms/room groups.
- Setting hours exceptions seems problematic because there's no way to enter one-off exceptions like in the hours management module; their suggestion for changing the duration of the booking doesn’t affect the public view for availability of the space, so we don’t understand those instructions
- Any way to remove the button for adding equipment? Why are spaced and equipment tied together? Patrons booking 102 don’t necessarily want a camera, and if they do, then is it going to lead to confusion (e.g. my camera will be waiting for me when I get to room 102)?
- No widget available yet; possibly coming soon (site says March 2017)?
- Doesn’t seem to be a way to set how far in advance rooms need to be booked (e.g. Stone requires 48 hours notice, as does the lobby)
- We're not crazy about how the dates on the calendar are highlighted when reserving a space; also, time selector tool is cumbersome
- It would be nice if for mediated rooms, the person approving reservations received a notification email that a reservation needed their attention
- Can’t seem to select multiple time slots; the only way to get the time reserved is by using the date/time picker, which as discussed above, is cumbersome. Also, it would disorienting for users who are accustomed to being able to do this with our current system

**Comment by cappadona** [comment] 2017-04-24 17:56
@eeh53 @sew268 Any updates from Springshare on our migration?

**Comment by sew268** [comment] 2017-04-24 18:22
@cappadona @eeh53 thanks for the reminder!  Just sent a follow up email; I'll let you know when I get a response.

**Comment by cappadona** [comment] 2017-05-05 14:46
Bumping to **May 2017** milestone. We've made some progress in the evaluation but are still in the middle of the migration. Tobi will add details on next steps.

**Comment by eeh53** [comment] 2017-05-05 14:51
We're waiting to see what changes will be coming with a May upgrade that LibCal should be putting out soon. We were told that the new features/improvements/fixes would be outlined in a blog post around the time of the release, so we're keeping an eye on that. 

Since the failed migration attempt to Spaces put all of CUL reservable rooms into the Uris location, we're concerned that may have implications for the launch of our reservable equipment service that we were hoping to launch mid-summer. Tobi is going to set up a meeting with OKU folks to see if they're still hoping to launch this new service over the summer so we can get a better sense of what our timeline for fixing this needs to be.

**Comment by cappadona** [comment] 2017-05-09 18:20
LibCal `2.7.0` was [released and announced today](http://blog.springshare.com/2017/05/09/libcal-2-7-0-now-live).

**Comment by sew268** [comment] 2017-05-09 18:45
## Issues with Spaces & Equipment Module `v2.7.0`
1. Hours are managed by location and not space.  We could set up separate locations so that we could tie them to department hours that we've entered in libcal, but that would be a lot of effort if this is something that springshare is going to resolve and we would have to think through the implications this would have for hours integration on CUL's site.

1. Email templates are not customizable by space. All correspondence would have to be generic and not include particular contact information or any specifics about the room itself.

1. Don't love the option to add equipment when booking a space (most noticeable from the public view) can we suppress this with the write API?

1. For mediated spaces, there is no way to set how far in advance users need to submit their requests, i.e. the reservation requests for Stone Classroom need to be 24 hours in advance so that staff can review and approve the reservation

1. Display when selecting multiple time slots from the public view is funky; looks better in the widget

1. Time selector for reservations from admin side isn't ideal

1. It would be nice if for mediated rooms, the person approving reservations received a notification email that a reservation needed their attention

**Comment by cappadona** [comment] 2017-08-31 15:15
@eeh53 @sew268 Still no official announcement on the SpringShare blog, but [widgets are working](http://spaces.library.cornell.edu/admin/spaces?action=widgets) so it appears the [August 2017 update](http://blog.springshare.com/2017/08/09/libcal-equipment-booking-update/) has been applied.

**Comment by cappadona** [comment] 2017-11-02 21:27
The (almost) October LibCal release was [deployed today](https://blog.springshare.com/2017/11/02/libcal-2-11-event-updates-and-more-are-live). No mention of tying hours to space or equipment categories in the post and I just confirmed that we're still out of luck 😞.

In better news, I reviewed the *Room Bookings* -> *Spaces* migration process and confirmed that our understanding of the two big concerns:

1. All _future_ reservations will be migrated
   > we'll still have access to past reservations in historical data
1. Once we finalize the migration, the Room Bookings module will disappear from our LibCal instance

> #### For more details on migration
> * [Blog Post](https://blog.springshare.com/2017/10/05/moving-from-libcal-room-bookings-to-spaces-more-functionality-more-features-more-fun)
> * [Official Docs](https://support.springshare.com/libcal/spaces-migration)

**Comment by cappadona** [comment] 2017-12-22 14:27
Now that we have our spaces setup in the E&S module, I went through and ran some tests to get a better idea about what this will mean for the Mann site for the time being until we are able to implement our [custom UX for reserving spaces](https://github.com/cul-it/mann-wagon/issues/915).

Here's a quick comparison of the two types of interactions our users have on the site based on room type.

## Study rooms, Lobby, Workstations (widget)

#### Before
<img width="538" alt="screenshot 2017-12-21 17 38 32" src="https://user-images.githubusercontent.com/409842/34301199-8d365fb8-e6f9-11e7-8b9b-e4d039455edb.png">

#### After
<img width="596" alt="screenshot 2017-12-21 17 38 55" src="https://user-images.githubusercontent.com/409842/34301251-d5d5db90-e6f9-11e7-9c3c-740e759f3e35.png">

## Conference rooms & Classrooms (public page)

#### Before
<img width="1305" alt="screenshot 2017-12-21 17 37 15" src="https://user-images.githubusercontent.com/409842/34301291-fd9ca3f2-e6f9-11e7-8c25-c4ac4b88d023.png">

#### After
<img width="1156" alt="screenshot 2017-12-21 17 37 46" src="https://user-images.githubusercontent.com/409842/34301303-09b34e5c-e6fa-11e7-8595-87f95b4b6346.png">

> Notice that currently (the before) we have only a single room/space per public page, but with the E&S module (the after), we'll have multiple spaces since the public page is tied to the category.

@eeh53 @sew268 Questions? Comments?

**Comment by cappadona** [comment] 2017-12-22 15:09
@eeh53 has split 100 and 102 into their own categories, so I think we're good to go, at least in terms of widgets and public pages. Tobi is currently working on email templates in the E&S module and will report back here.

**Comment by cappadona** [comment] 2018-01-19 13:53
Moving this to baked since the migration is going down today.

**Closed as completed** 2018-04-03 13:08 UTC
