### ISSUE TITLE
Spaces hours for cards and individual view

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#330] opened 2016-06-02 13:41 UTC

**Comment by tap87** [comment] 2016-06-02 14:05
@sew268 @tobi This comment is related to #331 as well. @cappadona and I discussed this issue and we need to confirm the following hours for the spaces (and feel free to add any that we missed):

1. Lobby -> From LibCal
2. Manndible -> From LibCal
3. Basement ClassRooms -> From LibCal
4. Reservable Study Rooms -> 30 minutes before the Library closes

**Comment by cappadona** [comment] 2016-06-02 14:48
Just updated Follett to use the basement hours from LibCal, which I believe is correct.

**Comment by sew268** [comment] 2016-06-06 20:43
@tap87 @cappadona Tobi and I have updated the list...let us know if you have any questions!

**Comment by cappadona** [comment] 2016-06-06 22:04
Keeping the original list around above, but here it is broken down into some categories. I have additional comments/questions that I'll add tomorrow.

### Library Hours
> Simple. Use primary library hours directly from LibCal. No tweaks, no exceptions.

1. 3rd Floor
1. Bisset Collaborative Center
1. Bissett Workstations
1. CIT MacLab - unaware of any reservation restrictions from CIT
1. CIT Lab - unaware of any reservation restrictions from CIT 
1. Gallery
1. Graduate Study Room
1. Group & Individual Study Rooms
1. One Button Studio
1. Stern Seminar Room
1. Stone Computing Center 

### Specific Location
> Also directly from LibCal but using hours for a *department* within the Library

1. Basement Classrooms: **Basement**
1. Follett Information Commons: **Basement**
1. Lobby: **Lobby**
1. Manndible: **Manndible**

### Exceptions
> Apply logic/math to hours retrieved from LibCal

1. Lobby Tabling: **Library** - unavailable 30 minutes prior to closing.
1. Mann 100 and 102: **Library** - unavailable for booking 30 minutes before the Library closes
1. Reservable Study Rooms: **Library** - 30 minutes before the Library closes
1. Stone Computing Center: **Library** - no reservations 30 minutes before closing
1. The Hive: **Library** - reservations restricted to M-Th 6pm-midnight during the week; reservations allowed during business hours on Saturday & Sunday

### Crazy Town
> Read it and weep

1.  Interview Room: (you're going to kill us:) ) follow basement hours during fall & spring semester, and follow building hours during winter break and summer.

**Comment by tap87** [comment] 2016-06-07 15:27
Thanks @sew268, @eeh53, and @cappadona. 
For the hive (as well as the interview room), should it be the same as other rooms, no reservations 30 minutes before closing.

**Comment by cappadona** [comment] 2016-06-07 15:56
@sew268 @eeh53 -- Additional followup as promised

1. For the exceptions, are we really talking about hours or just a limitation on when the spaces can be reserved? If it's the latter, can we stick with listing the straight-up hours and rely on the reservation system in question to enforce and inform the limitation?

1. As Tahir asked above for the Hive, instead of the hardcoded unavailable time of midnight M-Th, should it be whatever the closing time is for the **Library** or also 30 minutes prior?

1. I'm trying to understand how the Interview Room can be open while Follett is closed. Don't you need to walk through Follett to access the Interview Room?

**Comment by eeh53** [comment] 2016-06-14 17:27
@cappadona See my answers below:

1. I think it's fine to list the straight-up hours and rely on the reservation system in question to enforce the limitations. That's what we're doing now with the reservable spaces (Interview Room, One Button Studio) through LibCal (i.e. you can't reserve the room less than 30 minutes before).
2. I don't believe there's any limit on the Hive (or Interview Room, or One Button Studio) now, and it just follows the closing time of the library, but I could be wrong. I can double-check. Stay tuned.
3. Yes, you do. But we'll let people into the basement if they have a reservation for the Interview Room. It's complicated, but we just didn't want to block access to the Interview Room for the whole summer. I guess we could always revisit that decision, if it's causing major problems for showing the availability.

**Comment by tap87** [comment] 2016-06-14 17:46
@eeh53 I had a feeling that the 30 minute restriction isn't in place, otherwise the rooms should show as available during that period. It seems like you can reserve the room before slot's start time, and I am not exactly sure what that means.
![screen shot 2016-06-14 at 1 43 03 pm](https://cloud.githubusercontent.com/assets/4334244/16053290/23a5f85c-3236-11e6-8955-a00cc9e15456.png)

**Comment by eeh53** [comment] 2016-06-14 17:47
@tap87 I think that means you have to book it ahead of the time you want it, but that's just a guess. And you're correct, I just confirmed that the LibCal spaces do not have the 30-minute restriction and just follow building hours.

**Comment by cappadona** [comment] 2016-06-14 19:57
During today's review we decided:

* Move **reservable study rooms** to **library hours** category
* Move **interview room** to **specific location** category
  * Created #347 as potential enhancement down the road

> [Categories](https://github.com/cul-it/mann-wagon/issues/330#issuecomment-224102912) have been updated above to reflect these changes.

**Comment by sew268** [comment] 2016-10-10 22:30
@tap87 - rethinking this a bit after this morning's discussion.  I think we should not simply stick with 'open' or 'closed' for a room since doing that would involve another step for our users because they'd have to figure out how late a space is open to know if they can reserve/use it for the time they want.  

So I think we should say 'open till (or until) X'.  If the space is closed then I think it is ok to just say 'closed'.

For example on any given Tuesday during the regular semester when we close at Midnight, the availability for these locations would be the following:

Lobby Tabling: 'Open until 11:30PM' 
Mann 100 and 102: 'Open until 11:30PM' 
The Hive: Library - 'Open until Midnight' 
Lobby: 'Open 24hrs'

Does that make sense?? @eeh53 chime in if something looks amiss

**Comment by tap87** [comment] 2016-10-17 15:37
@sew268 Thanks, I think showing 'open until' is a good idea.
@cappadona Stone Computing Center is listed under Library Hours as well as Exceptions. Could you fix that. Maybe one of them is Stone Classroom.

**Comment by cappadona** [comment] 2016-10-17 15:42
@tap87 All set. **Stone Classroom** is the one with the exception.

**Comment by tap87** [comment] 2016-10-17 18:39
Deployed to dev. @cappadona @sew268 Let me know if everything looks good.

**Closed** 2016-10-21 19:10 UTC
