### ISSUE TITLE
Instruction request form

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#300] opened 2016-05-20 14:19 UTC
http://mannlib.cornell.edu/workshops-instruction/request-instruction

**Comment by dbranchini** [comment] 2016-08-08 11:43
This commit establishes the request instruction form - https://github.com/cul-it/mann-wagon/commit/bdd5beca38602873d62850a86bfc4d899b80898e.  The "type of instruction" field is not working correctly.  For some reason, it's not being submitted when the form is, so the user gets an error (because it's required) when they submit the form.  JS form validation (inline form validation errors) doesn't get triggered because it's actually filled in.

**Comment by dbranchini** [comment] 2016-08-08 11:46
Do we want to continue with Semantic-UI form validation?  It's kind of limited - regex is a possibility, but adding a custom function is not.  I was considering adding a call to a function for date checking (maybe using moment.js?) but inline custom functions are not a possibility with Semantic UI library.

**Comment by dbranchini** [comment] 2016-08-08 11:47
Should we have one JS file that contains all of the JS common to forms?  I'm seeing a lot of repetitive calls to JS components.

**Comment by dbranchini** [comment] 2016-08-08 11:50
Should we bring in the instruction group to verify these are the fields they want?  In one quick conversation I had with a librarian in this area, they suggested some of these fields might not be necessary but other questions might be relevant, such as expected learning outcomes.

**Comment by dbranchini** [comment] 2016-08-08 11:52
Last comment here (and this probably belongs somewhere else?) -- Tahir brought in an extension to semantic-ui for date selecting, but it seems to have brought it the entire semantic-ui library (in a different way than what we're doing already, so a second time).  We should figure out how to pull in just the relevant part.

**Comment by dbranchini** [comment] 2016-08-08 11:53
Just kidding - one more comment, I didn't dig too far into styles because I thought I'd leave this to Nick since he's been the primary developer on this.

**Comment by cappadona** [comment] 2016-08-09 17:11
The WIP form has been deployed to dev (`/help/faculty-instructors/request-course-instruction`).

**Comment by cappadona** [comment] 2016-08-11 19:45
See #352 re: validation library

**Comment by cappadona** [comment] 2016-08-11 20:29
semantic-ui duplication has been addressed with #431 & #436.

**Comment by cappadona** [comment] 2016-08-16 21:38
This was deployed to dev last week. I just tested the form while working on email notification in cul-it/mann-locomotive#17 and didn't run into the error with the `type of instruction` field as [Darcy reported earlier](https://github.com/cul-it/mann-wagon/issues/300#issuecomment-238212160).

**Comment by sew268** [comment] 2016-08-17 14:19
Will run form by Kelee for feedback

**Comment by sew268** [comment] 2016-08-18 12:42
Kelee's feedback:

Looks good... what does course web page mean?

The email should come to me:  klp92@cornell.edu
Do not think it needs to go to anyone else?
other than that.  I do not see any thing glaring right now.

@cappadona looks like 'course web page' is listed under type of instruction and it should be removed

**Comment by tap87** [comment] 2016-08-18 15:55
Remove "course web page" from dropdown.

**Comment by sew268** [comment] 2016-08-18 18:59
Just talked with Kelee again and 'course web page' was apparently what we used before libguides.  So, they want to keep it in but change the term to 'online research guide’.

**Comment by cappadona** [comment] 2016-08-22 14:06
Remove `course web page` option and add new field for *Interested in creation of online research guide?* boolean.

Multiple selection for course type?

**Comment by sew268** [comment] 2016-08-29 15:10
Checked with Kelee.  She's fine with the new field for the research guide and confirmed that she would like to keep the multiple selection functionality.

**Comment by cappadona** [comment] 2016-09-02 19:50
Deployed to dev. Please review messages in 386de3b and 586f78a for background information on implementing multiple selection for instruction type.

Using semantic-ui's dropdown component for multiple selection. I still fell pretty strongly that it has significant usability issues on mobile devices, but perhaps some of this will be addressed by #492.

**Comment by cappadona** [comment] 2016-09-02 19:59
P.S. Pay special attention to the **two** fields used in conjunction to support multiple-select

<img width="824" alt="screenshot 2016-09-02 15 58 46" src="https://cloud.githubusercontent.com/assets/409842/18216658/2a7feab4-7126-11e6-86a2-e928fde11860.png">

**Closed** 2016-09-12 20:22 UTC
