### ISSUE TITLE
Workshops & Classes (filtered events) on homepage don't always load

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#486] opened 2016-08-30 15:19 UTC
I've been noticing this recently and it happened once or twice during the staff show 'n tell last week as well (with one person commenting on it). No recipe to reliably reproduce this.

Just try requesting or refreshing the homepage...

**Comment by tap87** [comment] 2016-09-02 20:46
I was able to reproduce it finally, and it is happening in the events app so affects both the homepage and events page. It looks like the data isn't updated from previous methods for events, will use vue.js watch to get updated values.

**Comment by tap87** [comment] 2016-09-06 13:11
Fixed via [commit](2eeae7cbecb06781f11dda475bc650a0aee63152)

**Closed** 2016-09-12 20:10 UTC
Labels: bug, events
