### ISSUE TITLE
Usability testing for the exceptions on the full hours page

### ISSUE THREAD

**Issue by tap87** [cul-it/mann-wagon#63] opened 2016-02-09 14:06 UTC
Due to the lack of support in the api for exceptions, and the difficulty with templates for multiple day exceptions, we are going to conduct user testing on the necessity of displaying the exceptions on the hours page, as in the screenshot below:
![screen shot 2016-02-09 at 9 01 53 am](https://cloud.githubusercontent.com/assets/4334244/12918204/ccdc1912-cf0b-11e5-8647-f2795559aa6b.png)

**Comment by cappadona** [comment] 2016-04-11 15:15
Duplicate of #119

**Closed** 2016-04-12 14:14 UTC
Labels: duplicate, hours, hours-gem, usability
